// <auto-generated />
using System;
using Ausgaben_Management_App.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Ausgaben_Management_App.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Ausgaben_Management_App.Models.TbKategorie", b =>
                {
                    b.Property<int>("kategorieId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("kategorieId"));

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("Titel")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("kategorieId");

                    b.ToTable("TbKategorien");
                });

            modelBuilder.Entity("Ausgaben_Management_App.Models.TbTransaktion", b =>
                {
                    b.Property<int>("TransaktionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TransaktionId"));

                    b.Property<int>("Betrag")
                        .HasColumnType("int");

                    b.Property<DateTime>("Datum")
                        .HasColumnType("datetime2");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(75)");

                    b.Property<int>("kategorieId")
                        .HasColumnType("int");

                    b.HasKey("TransaktionId");

                    b.HasIndex("kategorieId");

                    b.ToTable("TbTransaktionen");
                });

            modelBuilder.Entity("Ausgaben_Management_App.Models.TbTransaktion", b =>
                {
                    b.HasOne("Ausgaben_Management_App.Models.TbKategorie", "kategorie")
                        .WithMany()
                        .HasForeignKey("kategorieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("kategorie");
                });
#pragma warning restore 612, 618
        }
    }
}
